-- 코드를 입력하세요
SELECT distinct CAR_RENTAL_COMPANY_CAR.CAR_ID
from CAR_RENTAL_COMPANY_CAR, CAR_RENTAL_COMPANY_RENTAL_HISTORY
where car_type = '세단' and MONTH(start_date) = 10 and CAR_RENTAL_COMPANY_CAR.car_id = CAR_RENTAL_COMPANY_RENTAL_HISTORY.car_id
order by CAR_RENTAL_COMPANY_CAR.CAR_ID desc